image: Visual Studio 2017

build:
  verbosity: minimal
  publish_nuget: false

skip_tags: false

test: off

init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version ($env:APPVEYOR_REPO_TAG_NAME).TrimStart("v")
    }

on_success:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        nuget push ".\build\Castle.Facilities.AutoTx.${env:APPVEYOR_BUILD_VERSION}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.IO.${env:APPVEYOR_BUILD_VERSION}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.Transactions.${env:APPVEYOR_BUILD_VERSION}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.Transactions.IO.${env:APPVEYOR_BUILD_VERSION}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
    }

build_script:  
  - cmd: build.cmd

artifacts:
 - path: build\*.nupkg
